export { default as turtle } from './turtle.avif';
export { default as michelleBlewitt } from './michelle-blewitt.avif';
export { default as water } from './water.avif';
export { default as water2 } from './water2.avif';
export { default as sandInHand } from './sandInHand.avif';
export { default as beach } from './beach.avif';
export { default as forest } from './forest.avif';
export { default as peopleWalk } from './peopleWalk.avif';
export { default as peopleCheck } from './peopleCheck.avif';
export { default as peopleTalk } from './peopleTalk.avif';
export { default as TIS } from './TIS.avif';
export { default as waterstains } from './waterstains.avif';
export { default as waterbubbles } from './waterbubbles.avif';
export { default as horizon } from './horizon.avif';
export {default as howStudentsCanHelp} from './howStudentsCanHelp.avif';
export {default as whatsNewInTheWorld} from './whatsNewInTheWorld.avif';
export {default as MappingMicroplastics} from './MappingMicroplastics.avif';
export {default as ManlyCove} from './ManlyCove.avif';
export {default as WorstMicroplastic} from './WorstMicroplastic.avif';
export {default as AwesomePlastic} from './13AwesomePlastic.avif';